### ISSUE TITLE
KitKat support

### ISSUE THREAD

**Issue by Human** [ibaton/3House#1]
When I run the app on an API 19 emulator, I get this:

`java.lang.RuntimeException: Unable to start activity ComponentInfo{treehou.se.habit/treehou.se.habit.MainActivity}: java.lang.IllegalArgumentException: AppCompat does not support the current theme features`

I'll see if I can find the root cause.

**Comment by ibaton** [comment]
Awesome that you found this so soon.
Pushed up a build without this fix this morning. 

Will have to push up a new one asap.
