### ISSUE TITLE
support self-signed certificates

### ISSUE THREAD

**Issue by Human** [ibaton/3House#18]
Of the 20 current Play Store reviews, one 1-star review is by someone with a self-signed SSL cert. [Here](https://developer.android.com/training/articles/security-ssl.html#SelfSigned) are guidelines for supporting it. Maybe we can turn that 1-star review into a 5-star review.

**Comment by ibaton** [comment]
Yes we should really fix this.
But will require quite a lot of time to implement as there are multiple network libraries in play.

The client currently has a hack making it accept all Certificates.
Really bad for security.

**Comment by ghost** [comment]
Hi,
With self signed certifcate could you add the possibility to choose a certificate in android store or other when client side authentication.
Thank you.
Gilles.

**Comment by ghost** [comment]
Openhab client application can now use client side authentication. Is it possible to implement that ?

**Comment by ibaton** [comment]
fixed
