### ISSUE TITLE
remember sitemap selection

### ISSUE THREAD

**Issue by Human** [ibaton/3House#20]
When the app (re)starts, it asks again which sitemap to use. As sitemap selection is already available via the drawer, let's re-use the last-chosen sitemap. The user is free to choose an alternate via the drawer menu.

**Comment by Human** [comment]
I see now that there is a feature to support this, but it's off by default. Do you think we should just turn it on by default? In case you do, I'll submit a change for this.

**Comment by Human** [comment]
Hmm, on further investigation, it doesn't seem to be as simple as turning it on by default, since the mechanism requires you to choose a default sitemap.

Would you be open to the idea of removing this feature, as implemented, and just having it re-use whatever sitemap was chosen last?

**Comment by ibaton** [comment]
Yeah, Sounds like a great Idea. 
Most people wont touch the settings anyway.

**Comment by Human** [comment]
https://github.com/ibaton/3House/pull/26

**Comment by Human** [comment]
Can we close this now, or is there more left to do?

**Comment by ibaton** [comment]
@Human 
Sorry for the delay, We can close it. 
Does works really nice
