### ISSUE TITLE
Selection items send commands when shown on page

### ISSUE THREAD

**Issue by gersilex** [ibaton/3House#22]
If there is a _Selection_ item on the sitemap, it instantly sends a command to openHAB with the current selection. Even if it was already set.
### expected behavior

Selection items should only send commands after a selection has been done (e.g. closing the dropdown)

**Comment by ibaton** [comment]
Thanks @gersilex made a fix it. Will push it out tomorrow.

**Comment by gersilex** [comment]
Thanks. If there is a place for your pre-playstore apks, just let me know. I like your project and try to build my WIP smart home mostly on your frontend including all features including widgets and your tasker/locale plugin. So expect more issue contributions to come ;)

**Comment by gersilex** [comment]
:white_check_mark: fix confirmed.

**Comment by ibaton** [comment]
@gersilex 
Epic. Will do the best i can to satisfy your needs.
