### ISSUE TITLE
Colorpicker widget lacks ON/OFF/INCREASE/DECREASE buttons

### ISSUE THREAD

**Issue by gersilex** [ibaton/3House#23]
The Color Items is capable of more commands than just a HSB color object.

For intuitive usage of lights, we should implement the on/off buttons as well:
- :arrow_up_small: 
  - push: send command ON
  - hold: send command INCREASE (repeatedly)
- :arrow_down_small: 
  - push: send command OFF
  - hold: send command DECREASE (repeatedly)

There would also be a possibility to send Percent objects to the color item, which could be used for dimming the current color, without changing the color mix. But I think the current color selection implementation works perfectly fine for dimming (outer ring).

I am not sure how we could visualize the two additional buttons without being too obstrusive. We can collect ideas here.

**Comment by ibaton** [comment]
@gersilex @Human 
Thoughts suggestions?

![screenshot_2015-07-14-00-18-15](https://cloud.githubusercontent.com/assets/448200/8662223/f10b576a-29bd-11e5-9110-538f1a629c75.png)

**Comment by gersilex** [comment]
Looks good, if these are Color Items, how am I supposed to choose a color (HSBColor Obect) now?

Clicking on the text would be working but maybe isn't so obvious.

Also, is the bar between the icon and the Text Label representing the current color? That would be awesome.

There is not much space left, maybe we could "expand" the colored bar, as soon as one of the buttons have been pressed to show users, that there is more to click. we could expand it so a square with a Colorwheel on top of it.

Just some thoughts, all of them sound hard to program. Any other suggestions?

Thanks for the concept!

**Comment by ibaton** [comment]
Yep. Those are color items.
Clicking anywhere except the buttons will open the color picker.

Tried having a larger color bar but it looked strange and offseted the text to much. And the other logic would be quite hard to implement.

I'm pushing up the code for the layout in the meantime and closing this issue. 
Could move back to this widget when we figure out a better design.
