### ISSUE TITLE
Charts not working over http basic auth https remote url

### ISSUE THREAD

**Issue by gersilex** [ibaton/3House#25]
When using 3House over a https connection, which is secured with a username and password (http basic auth from openhab), charts are not working, because the request is faulty.

This is what openhab logs:
`2015-06-14 23:24:29.173 [WARN ] [.io.net.http.SecureHttpContext] - authInfos '�)^��q���"Č' must contain two elements separated by a colon`

Other items work fine.

**Comment by neoscaler** [comment]
Can confirm this issue, experiencing it too.

**Comment by ibaton** [comment]
Sorry for the wait guys @gersilex  @7Bit . 
I think that I have managed to find the problem.

Will have it pushed to play in a couple of days.

**Comment by neoscaler** [comment]
No problem, thanks for the great work. Awaiting the release :+1:

**Comment by ibaton** [comment]
@7Bit @gersilex 
Pushed a new version up to Play.
Would be great if you can tell me when you have tried it out and if it woks.

**Comment by gersilex** [comment]
Thank you very much for the update. The issue however is not solved.

The error message does not occur anymore, but it seems like there isn't even a chart being requested now. The Charts still appear empty.

In the OpenHAB Server there are no logs in the `openhab.log`. But if you look inside the `requests.log` you will see that there isn't even a request for the charts:

`requests.log`

```
212.79.14.23 -  -  [11/Aug/2015:13:59:53 +0000] "GET /rest/sitemaps/default/0200/ HTTP/1.1" 200 863 
212.79.14.16 -  -  [11/Aug/2015:13:59:53 +0000] "GET /images/bathroom.png HTTP/1.1" 200 505 
212.79.14.18 -  -  [11/Aug/2015:13:59:53 +0000] "GET /images/bathroom.png HTTP/1.1" 200 505 
```

Can we provide any application logs from 3House or something?

**Comment by neoscaler** [comment]
Again, I can confirm what gersilex said. No errors anymore, but no requests in log file and no chart is shown.

**Comment by ibaton** [comment]
Strange. Fixed another problem that could have caused it (good to have that out of the way at least).

Could you throw over your sitemap and items related to the the chart widget.
Alternatively better if you can give me temp access to the sitemap.

**Comment by neoscaler** [comment]
Correction: Charts are working for me if I am at home via wifi. But not from via remote URL.

**Comment by ibaton** [comment]
Found it. It was always fetching the charts from local network if one where present.
Pushing up a new build later today.

**Comment by gersilex** [comment]
Awesome, I'm waiting impatiently :+1: you are awesome.

**Comment by neoscaler** [comment]
Now I am seeing charts from remote, unfortunately they are empty. We are not there yet :)

**Comment by gersilex** [comment]
Confirmed. They are there, but are empty.

The reason is, that the charts are now requested without any data:

3House requests: `GET /chart HTTP/1.1" 200 2946` -> Default Chart without items= or groups= set
HABdroid requests: `GET /chart?groups=temperaturen&period=W&random=-511668451&w=1080&h=540` -> Chart of all items of group **temperaturen** with a time range of **one week** and dimensions of **540x1080px**

Tested from Remote HTTPS URL

**Comment by ibaton** [comment]
Still problems in the latest update?

**Comment by gersilex** [comment]
:white_check_mark: confirmed working. Thank you very much!

**Comment by ibaton** [comment]
Epic @gersilex . 
Also managed to solve a couple of unrelated chart problems in the process.
