### ISSUE TITLE
make full row clickable

### ISSUE THREAD

**Issue by Human** [ibaton/3House#3]
If a row has a single tappable item in it, make the whole row tappable instead.

Example:
![screenshot_2015-05-02-11-16-41](https://cloud.githubusercontent.com/assets/40866/7441604/ffc1b4c8-f0bc-11e4-8e54-735622f5faea.png)

The rows here with a ">" icon in them are only tappable on the icon. The entire row should respond to a tap. The same would be true of rows representing binary switches.

Things like sliders would be exempt from this change.

**Comment by ibaton** [comment]
We will probably have to make some of the other widgets like the color widget distinct from text widgets. 

Example:
A color item with an associated page would look like an item with an associated page.

My suggestion is to either: 
1. Make the widgets more distinct before introducing the functionality
or
2. Add a vertical line before the arrow on widgets where the next page button doesn't apply to the whole widget.

**Comment by Human** [comment]
Can you provide an example sitemap that produces each of the cases you described? I can try out some layout options and provide screenshots of various approaches to make sure we cover all the cases you described.

Actually, now that I think of it, it'd be a good idea to have a test sitemap with every possible scenario in it anyway, just as a coverage test.

**Comment by ibaton** [comment]
@Human 
Forget what said. 
Seems like color items shouldn't be able to have a page.
We should absolutely make the whole item clickable.

Great idea with the sitemap. 
We should absolutely do that covering all the cases.
I'll throw it up as an new issue.

**Comment by Human** [comment]
See PR https://github.com/ibaton/3House/pull/15

**Comment by ibaton** [comment]
@Human 
Epic work. I have merged and will include it in Tonight's build for the playstore.

**Comment by Human** [comment]
Woo!
