### ISSUE TITLE
Switch items with only 1 mapped command are hidden

### ISSUE THREAD

**Issue by gersilex** [ibaton/3House#31]
I have some `Switch` items, that only have one specific function, instead of multiple or the default `OnOffType` switch type:

`default.sitemap`

```
Switch item=devices_leroy mappings=[OFF="Alles Abschalten"] visibility=[devices_leroy>0]
```

Those sitemap entries are completely hidden.
## Expected behavior

The sitemap entries should **be shown** _and_ should **look like a button instead of a radiobox**.
The button **should clearly indicate that it is still active** (like an enable radiobox stays enabled)
It should not be "unpressable".

We can discuss, how we can show that the button is pressen. I would think about letting it look like "pushed in", but in flat design this would not fit.

**Comment by ibaton** [comment]
@gersilex 
What do you think about using a dropdown to select the different entires?

**Comment by ibaton** [comment]
Should already be like this in OpenHAB v1. 
But it appears that the JSON field has changed from "binding" to "bindings" in v2 which messes up the parsing.

**Comment by ibaton** [comment]
Sorry misread the issue at first. 
Have made an update for the widget.
