### ISSUE TITLE
Switch Items with 1 mapping send commands when being rendered

### ISSUE THREAD

**Issue by gersilex** [ibaton/3House#33]
The feature added in #31 causes the Switch (Button) to send its command when it is rendered in 3House.

This behavior clones the issue from #22 
## Reproduction
- Kill 3House App
- Open App
- Sitemap displays a switch item with single mapping (see feature #31)
- 3House sends the command, even if not pushed.
## Expected behavior

The button is only pressed when being pushed by the user
## Thoughts

This may happen, when Switch is already in its state, the mapping would show. For Example:
- User presses Button "Turn Off All"
- This maps to `OFF` of the Switch Item `devices_turn_off_all`
- User closes app
- User opens app again
- App sees that "Turn Off All" is in `OFF` State and sends command (but should not!)

**Comment by ibaton** [comment]
Stupid mistake from my end. 
Missed some debug code. 
Fix coming up right away.

Btw, Great issue descriptions, helps out a lot.
