### ISSUE TITLE
[BUG] Graphs are not showing when using mysql persistence

### ISSUE THREAD

**Issue by kkmaslowski** [ibaton/3House#35]
Graphs are empty when I use mysql persistence.

Request log when accessing from web browser (chrome):
127.0.0.1 -  -  [26/Aug/2015:19:18:11 +0000] "GET /chart?items=Temperatura_Cyrkulacja&period=D&random=1&service=mysql HTTP/1.1" 200 10020 

Request log from application:
127.0.0.1 -  -  [26/Aug/2015:19:16:30 +0000] "GET /chart?items=Temperatura_Cyrkulacja&period=D&random=968512915 HTTP/1.1" 200 2930

**Comment by ibaton** [comment]
Thanks for the report @kkmaslowski 
Haven't actually seen the "service=*" parameter before, I'll take a look at it and see whats wrong.

**Comment by ibaton** [comment]
@kkmaslowski I have pushed an update. 
Will be in next version of app.

**Comment by kkmaslowski** [comment]
Hi. I managed to fix this. I removed jar for rrd4j. Now I have only mysql persistence and graphs are showing correctly. When I had both jars it was not working.
Someone had the same problem: https://groups.google.com/forum/#!topic/openhab/SmwmwXLJDvs
