### ISSUE TITLE
Translation - German 

### ISSUE THREAD

**Issue by ibaton** [ibaton/3House#38]
## What:

Should translate the app into German
Both in app and promo text for the play store.
## Why:

Most people find it nice to have app translated in their own language.
There are as many German users as English users and it would be appropriate to have it translated in both languages.
## How:

Go to http://os9rldd.oneskyapp.com/ and start translating

**Comment by pravussum** [comment]
Almost done. Need a comment for the "At you command" translation, though... didn't find it in the app to get the context.
I commented in the translation center, so have a look there, if you please...
I think the UI labels need some fine tuning anyway, but one step after the other :-)

**Comment by ibaton** [comment]
@pravussum  The "At you command" text is for when you are using the voice commands.
Its should be like your personal robot assistant asking you what you want ^_^

**Comment by pravussum** [comment]
Ok, done - should suffice for an initial version...

**Comment by ibaton** [comment]
Great work @pravussum I'll throw it in the next app version.
Would it be OK if I mention you in the update notes in the app store?

**Comment by pravussum** [comment]
Ok, cool. Sure.
