### ISSUE TITLE
Labels are not cropped / bad looking line breaks 

### ISSUE THREAD

**Issue by pravussum** [ibaton/3House#39]
See attached Screenshot - the "Treppenfenster" item showing the percentage value is unnecessarily line-broken 3 times.

![screenshot_2015-08-31-10-42-48](https://cloud.githubusercontent.com/assets/5208777/9575133/66eda5a2-4fcd-11e5-88f3-ae9f19624133.png)

**Comment by ibaton** [comment]
Thanks @pravussum, That looks really awful.
Will probably have time to fix it this weekend.

**Comment by ibaton** [comment]
I have fixed this problem. 
Will be included in next version.

**Comment by pravussum** [comment]
:+1:
