### ISSUE TITLE
NPE in VoiceCellBuilder

### ISSUE THREAD

**Issue by pravussum** [ibaton/3House#40]
NullPointer in treehou.se.habit.ui.control.builders.VoiceCellBuilder$1, line 41

Happens when clicking on the "button" of a controller inside the app (not a widget).
If I remember correctly i fiddled around with "Voice" commands yesterday, without knowing what I'm doing.
The reason is probably that I didn't configure any voice related stuff in openhab and thus 3House didn't load any items into the controllers items dropdown... so I didn't choose any item and the controller was saved like this (item null).

If you need the full stacktrace, let me know... got a screenshot - didn't want to send it via Google, though.

**Comment by ibaton** [comment]
@pravussum 
I think that will be enough to find the problem.
Thanks

**Comment by pravussum** [comment]
Confirmed for working.

**Comment by ibaton** [comment]
@pravussum Epic and big thanks for helping out
