### ISSUE TITLE
"Lost connection to server" error for every item in sitemap

### ISSUE THREAD

**Issue by pravussum** [ibaton/3House#49]
I've got a sitemap with several groups for all the rooms in the house and so on.
No matter which of the groups i choose in the current release, it always fails with error "Lost connection to server". Tried a couple of times with different networks (VPN, Wifi at home, ...) - always the same.

**Comment by pravussum** [comment]
Just debugged.
WidgetDeserializer line 58 receives json "1.0" (step object) and tries to parse it as int -> NumberFormatException.
This is obviously a valid use case since I didn't do any magics with my sitemap / items definition. 
So either change value and step type in Widget class to Double or try to parse JSON input as Double in case of NFE and cast to Int. 
Do you want me to file a pull request? 

BTW: How do you log? I'm coming from an enterprise Java application world and only have rudimentary Android experience...
Anyway, logging is quite useless on a mobile, isn't it?

**Comment by ibaton** [comment]
@pravussum Sorry for not getting back to you sooner.
Starting a new job and lots to do.

Changing the step type in integer to double or float feels like the right way to go.
It would be awesome if you would like to do a Pull request for it. But I can do it if you like if its troublesome.

Logging is kind of useless for mobile. 

Log.d(String tag String message) 
Quite nice for debugging purposes, but its not stored or anything like that.
