### ISSUE TITLE
Crash when using decimal step value

### ISSUE THREAD

**Issue by TheNetStriker** [ibaton/3House#59]
The app crashes when I'am loading a page with a Setpoint widget with a decimal step value E.g.:

``` <widget>
<widgetId>0002_0_0_1_2_3_4</widgetId>
<type>Setpoint</type>
<label>Temperature</label>
<icon>none</icon>
<minValue>16</minValue>
<maxValue>28</maxValue>
<step>0.5</step>
<item>
<type>NumberItem</type>
<name>NUM_Temperature</name>
<state>21</state>
<link>
http://172.17.2.21:8080/rest/items/NUM_Temperature
</link>
</item>
</widget>
```

I found the following error in logcat:

11-24 11:40:07.502 E/Communicator(9311): Received page error http://172.17.2.21:8080/rest/sitemaps/default/0002/
11-24 11:40:07.502 E/Communicator(9311): retrofit.RetrofitError: Invalid int: "0.5"
11-24 11:40:07.502 E/Communicator(9311):    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:400)
11-24 11:40:07.502 E/Communicator(9311):    at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
11-24 11:40:07.502 E/Communicator(9311):    at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
11-24 11:40:07.502 E/Communicator(9311):    at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
11-24 11:40:07.502 E/Communicator(9311):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-24 11:40:07.502 E/Communicator(9311):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-24 11:40:07.502 E/Communicator(9311):    at retrofit.Platform$Android$2$1.run(Platform.java:142)
11-24 11:40:07.502 E/Communicator(9311):    at java.lang.Thread.run(Thread.java:818)
11-24 11:40:07.502 E/Communicator(9311): Caused by: java.lang.NumberFormatException: Invalid int: "0.5"
11-24 11:40:07.502 E/Communicator(9311):    at java.lang.Integer.invalidInt(Integer.java:138)
11-24 11:40:07.502 E/Communicator(9311):    at java.lang.Integer.parse(Integer.java:410)
11-24 11:40:07.502 E/Communicator(9311):    at java.lang.Integer.parseInt(Integer.java:367)
11-24 11:40:07.502 E/Communicator(9311):    at java.lang.Integer.parseInt(Integer.java:334)
11-24 11:40:07.502 E/Communicator(9311):    at com.google.gson.JsonPrimitive.getAsInt(JsonPrimitive.java:260)
11-24 11:40:07.502 E/Communicator(9311):    at treehou.se.habit.connector.serializers.WidgetDeserializer.deserializeWidget(WidgetDeserializer.java:58)
11-24 11:40:07.502 E/Communicator(9311):    at treehou.se.habit.connector.serializers.WidgetDeserializer.deserialize(WidgetDeserializer.java:105)
11-24 11:40:07.502 E/Communicator(9311):    at treehou.se.habit.connector.serializers.WidgetDeserializer.deserialize(WidgetDeserializer.java:18)
11-24 11:40:07.502 E/Communicator(9311):    at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
11-24 11:40:07.502 E/Communicator(9311):    at com.google.gson.Gson.fromJson(Gson.java:810)
11-24 11:40:07.502 E/Communicator(9311):    at com.google.gson.Gson.fromJson(Gson.java:875)
11-24 11:40:07.502 E/Communicator(9311):    at com.google.gson.Gson$1.deserialize(Gson.java:128)
11-24 11:40:07.502 E/Communicator(9311):    at treehou.se.habit.connector.serializers.WidgetDeserializer.deserializeWidget(WidgetDeserializer.java:69)
11-24 11:40:07.502 E/Communicator(9311):    at treehou.se.habit.connector.serializers.WidgetDeserializer.deserialize(WidgetDeserializer.java:105)
11-24 11:40:07.502 E/Communicator(9311):    at treehou.se.habit.connector.serializers.WidgetDeserializer.deserialize(WidgetDeserializer.java:18)
11-24 11:40:07.502 E/Communicator(9311):    at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
11-24 11:40:07.502 E/Communicator(9311):    at com.google.gson.Gson.fromJson(Gson.java:810)
11-24 11:40:07.502 E/Communicator(9311):    at com.google.gson.Gson.fromJson(Gson.java:875)
11-24 11:40:07.502 E/Communicator(9311):    at com.google.gson.Gson$1.deserialize(Gson.java:128)
11-24 11:40:07.502 E/Communicator(9311):    at treehou.se.habit.connector.serializers.LinkedPageDeserializer.deserialize(LinkedPageDeserializer.java:56)
11-24 11:40:07.502 E/Communicator(9311):    at treehou.se.habit.connector.serializers.LinkedPageDeserializer.deserialize(LinkedPageDeserializer.java:18)
11-24 11:40:07.502 E/Communicator(9311):    at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
11-24 11:40:07.502 E/Communicator(9311):    at com.google.gson.Gson.fromJson(Gson.java:810)
11-24 11:40:07.502 E/Communicator(9311):    at com.google.gson.Gson.fromJson(Gson.java:775)
11-24 11:40:07.502 E/Communicator(9311):    at retrofit.converter.GsonConverter.fromBody(GsonConverter.java:63)
11-24 11:40:07.502 E/Communicator(9311):    at treehou.se.habit.connector.BasicAuthServiceGenerator$OpenHabConverter.fromBody(BasicAuthServiceGenerator.java:90)
11-24 11:40:07.502 E/Communicator(9311):    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:367)
11-24 11:40:07.502 E/Communicator(9311):    ... 7 more
11-24 11:40:07.502 D/PageFragment(9311): error java.lang.NumberFormatException: Invalid int: "0.5" Invalid int: "0.5"

Please change this variable to a decimal type.

**Comment by ibaton** [comment]
Thanks @TheNetStriker will take a look at it this weekend

**Comment by ibaton** [comment]
Hi @TheNetStriker, @pravussum actually fixed this 2 months ago. 
I guess I somehow must have forgot to merge the change before building the apk.
