### ISSUE TITLE
Crash when removing server

### ISSUE THREAD

**Issue by clach04** [ibaton/3House#61]
Press and hold to remove a server when there are no servers causes a crash on my device. Using latest version from Play store.

**Comment by clach04** [comment]
What's the best way to deal with this pre-fix? Uninstall and then install?

**Comment by ibaton** [comment]
@clach04 The fix is currently to uninstall or clear all app data. 
This will recreate the DB with the new setup.

I (or possible @tylerwhall who wrote the fix) might write up a migration script when there is time, but it's not in there right now.

**Comment by clach04** [comment]
uninstall/install is fine for me.
