### ISSUE TITLE
How to create a new activity layouts in your 3House.

### ISSUE THREAD

**Issue by amarpulli1994** [ibaton/3House#69]
Hello,
I want create new button in item_sitemap.xml.How did do the this kind of task in 3House.How to write the  button java class,where I write the button java class in 3House.In this task whenever I click the button open the another activity.please reply me...wait for your response.

**Comment by ibaton** [comment]
There is to my knowledge not any way way of modifying the item_sitemap sitemap through the openhab api. It has to be done through modifying the xml on the openhab server. 

A sitemap like this

```
Text label="Group Demo" icon="1stfloor" {
                Switch item=Lights mappings=[OFF="All Off"]
                Group item=Heating
                Group item=Windows
                Text item=Temperature
         }

```

Will open in a new fragment, not in a new activity though, but it shouldnt be to hard to modify
