### ISSUE TITLE
How to create a user customization profiles in 3House? 

### ISSUE THREAD

**Issue by amarpulli1994** [ibaton/3House#70]
Hello,
I need to  developing the some new feature in 3House.I create a add profile option to the user.When user create a profiles like"Home,Away,Day,Night".
![screenshot from 2016-03-29 12-00-34](https://cloud.githubusercontent.com/assets/16384828/14100024/f6da97f8-f5a7-11e5-8715-bdd382258230.png).
How to implement the this kind task in 3House.Where,I did the changes and writing the some code.
In above screen shot,Whenever user clicking the "Add Profiles" open the another actvity layout.
![screenshot from 2016-03-29 12-06-47](https://cloud.githubusercontent.com/assets/16384828/14100124/afa3ef64-f5a8-11e5-8b96-8c2e3f2185e7.png).
Whenever user create a profiles like"Home,Away,Day,Night",saved under "Add Profiles".like below the screen shot.How to save the user profiles and create a database for user profiles.
![screenshot from 2016-03-29 12-04-00](https://cloud.githubusercontent.com/assets/16384828/14100174/1ad2f514-f5a9-11e5-9851-7c9e30c76c9c.png).
The user choose option "HOME" having the sitemaps and items.like below screen shot
![screenshot from 2016-03-29 12-26-59](https://cloud.githubusercontent.com/assets/16384828/14100482/744b4b8a-f5ab-11e5-88a9-a4d166dc6a3a.png).
The user enter into the sitemaps and selected some items and saveit at the time not able to activate the items,the user return to the home page like"Home,Away,Day,Night".When user click the Home at taht time only activate the selected items.How to save the selected items in openhab.Then,How did do the this task in 3House.Please help me...wait for your response.
Thanks.
Amar.

**Comment by ibaton** [comment]
Hi @amarnathreddy44  Im not sure why you would want to do this in this way.
The easiest way to create a profile would probably be to create a new sitemap item.
Like:

`Selection item=Yamaha_Living_Input mappings=[AV1="TV",  HDMI4="Steam Link", HDMI5="Google Tv"]`

And controll it through rules on the server

**Comment by kirantpatil** [comment]
@ibaton, the rules had to be predefined in the server and what @amarnathreddy44 is trying to do is customize the profile at client by user and store the state in the app itself.

Ex: Suppose we have 4 items (1 bulb, 1 fan, 1 door, 1 window)

Profile Day: bulb => on, fan => on, window => open, door => close

Profile Night: bulb => off, fan => off, window => close, door => close

Now user can add/modify the items and its commands at client and apply them based on his needs.

@amarnathreddy44 please correct me if I am wrong in my explanation.

please find the screenshots here.
![cd062a0d29505ef0d4c846e6b984cd02572c6ce9_1_140x250](https://cloud.githubusercontent.com/assets/1178055/14132860/d3090240-f667-11e5-9955-5324e9065392.png)
![08fb1de74cd2d6cb5cc46ae66f128bd3db35bcda](https://cloud.githubusercontent.com/assets/1178055/14132861/d677fa1c-f667-11e5-99d7-ccf68f5267d0.png)

**Comment by ibaton** [comment]
The way to do it would be to create a active Android model object like the ones in https://github.com/ibaton/3House/tree/develop/mobile/src/main/java/treehou/se/habit/core/db

The database would automatically be set up automatically when data is cleaned or app is uninstalled.

I'm currently working on moving away from active Android to realm.io, it will break a lot of database calls.  It will probably take a couple of weeks before the change is finished, but it could be worth the wait. I have uploaded a branch with the progress at https://github.com/ibaton/3House/tree/develop-extract-network quite a lot of stuff still not working there though

**Comment by amarpulli1994** [comment]
Hello,
I need to create a "Add Profile" button in layout of item_sitemap.xml like this
![screenshot from 2016-03-29 12-00-34](https://cloud.githubusercontent.com/assets/16384828/14198003/ed4cb444-f7f2-11e5-878e-42c10632a8b2.png).
When user wants to adding a new profile's like "Home,Day,Night...etc".When user press the "Add Profile" button open the another layout like this
![screenshot from 2016-03-29 12-06-47](https://cloud.githubusercontent.com/assets/16384828/14198094/fa28ae6a-f7f3-11e5-9450-f4f87e9f8fcb.png).
The user enter the profile's.The profile's save under the "Add Profiles" in layout of item_sitemap.xml.like this
![screenshot from 2016-03-29 12-04-00](https://cloud.githubusercontent.com/assets/16384828/14198151/77c0ed7e-f7f4-11e5-9b38-ef6f98f22a04.png).
The user pree the "Home" profile, it will open the sitemap home page like this
![screenshot from 2016-03-29 12-26-59](https://cloud.githubusercontent.com/assets/16384828/14198172/c51cc872-f7f4-11e5-8544-6440d861973b.png).
I want to do these tasks in app itself.Then,How to do?. I easily created a "Add Profiles" button but where i did write  the button code in 3House.It's user customization profile's. For example user going to outside.The  user already creating profile name as "Away",the user press the "Away" in that what are the selected items to be activated at that moment.How to do this task in 3House.Please help...wait for your response.
System Environments:
Operating system: Fedora 22(64 bit).
Android Studio:Android Studio 2.0 beta6.
Java:Java 1.8
Thanks,
Amar.
