### ISSUE TITLE
 We are creating a add profiles in app for user's.

### ISSUE THREAD

**Issue by amarpulli1994** [ibaton/3House#71]
Hello,
   We need to provide a options to user,that option name is "add profiles". How to make the this kind of activity in 3House.I want to do the task in app itself.In previous question showing the some screen shots,the user creating the own profile in application. The user creating a profile name is "Day",the profile name saved under "Add Profiles". The user click the "Day" it's open the Sitemap's .At that time user selecting the items and save it in openhab sitemap server.How to save the selected items in openhab server.The selected items not able to activate at that moment.When user click the profile name:"Day" at that only  activate the selected items.
Ex: Suppose we have 4 items (1 bulb, 1 fan, 1 door, 1 window)

Profile Day: bulb => on, fan => on, window => open, door => close

Profile Night: bulb => off, fan => off, window => close, door => close

Thanks,
Amar.

**Comment by ibaton** [comment]
It is not possible to save a custom sutemap it on the server through the app (There is no api calls for it). It would have to be on the server itself. 

Do you want to do this in the client? It would probably be easier to do on the openhab server with items and rules.
