### ISSUE TITLE
How to create a rest api services for user customization profile's?

### ISSUE THREAD

**Issue by amarpulli1994** [ibaton/3House#77]
Hello,
In 3house how to create a "rest  api's" for user customization profile's.Where I create a "rest api's" in your 3house.The  openhab architecture 
![images](https://cloud.githubusercontent.com/assets/16384828/14451200/bea5733e-00a2-11e6-81f5-f25d0e313b4e.png).
The rest api services where is located in your 3house.how to write the rest api's accessing the user profiles .Where I need to write code for like add profiles button,save profiles,etc.please help me..
Thanks,
Amar.

**Comment by ibaton** [comment]
The rest api can be found here
https://github.com/ibaton/3House/blob/2a58462012124463f5191c8b0350a6b7d77d91b1/ohcommunicator/src/main/java/se/treehou/ng/ohcommunicator/connector/OpenHabService.java

But openhab doesnt have any rest path for location.
