### ISSUE TITLE
Adding the user customization profile in 3 House application?

### ISSUE THREAD

**Issue by amarpulli1994** [ibaton/3House#81]
Hello,
I need to add new feature to 3 House application for OpenHAB Home automation.According to my understanding will give flowchart of how to add user customization profile
![openhab](https://cloud.githubusercontent.com/assets/16384828/14640450/3d3b099a-065f-11e6-9c7a-7e039caa90ce.png).
Where I put it code for working the "Add Profile" Button in your 3House.I creating the "Add Profile" button in sitemap.xml layout file .![screenshot from 2016-03-29 12-00-35](https://cloud.githubusercontent.com/assets/16384828/14640906/64b84a94-0661-11e6-91ba-9a79255c0114.png)
In this flow chart user profile saved into the database.The OH Communicator fetching user profiles and  providing the sitemaps and items to that user profiles.That user Profiles display like below screenshot![screenshot from 2016-03-29 12-04-00](https://cloud.githubusercontent.com/assets/16384828/14640949/8d787030-0661-11e6-9d8b-9741dd09b0d1.png).
Thanks,
Amar.

**Comment by ibaton** [comment]
Hi Amar. You can now use Realm.io to save the profile in database.
https://realm.io/. 

Create a profile object extending RealmObject.
Then use get the realm default and save it with

```
Realm realm = Realm.getDefaultInstance();
realm.beginTransaction();
realm.copyToRealmOrUpdate(profile);
realm.commitTransaction();
```
