### ISSUE TITLE
Hoe to create a SQLiteDatabase in android studio?How to store and retrive the data in SQLiteDatabase?

### ISSUE THREAD

**Issue by amarpulli1994** [ibaton/3House#82]
Hello,
I want to create a database for storing the user profiles.I will keep user profiles options top of the sitemap layout page like menu option item selected the code given as below screen shots
![screenshot from 2016-04-28 17-29-32](https://cloud.githubusercontent.com/assets/16384828/14885063/cdcc2daa-0d66-11e6-812b-66828b8aeb7f.png)
![screenshot from 2016-04-28 17-31-17](https://cloud.githubusercontent.com/assets/16384828/14885091/0b72d424-0d67-11e6-8ed9-d98e32b696de.png)
Whenever user want to select the "AddProfile" options it will open "Enter user profiles" layout
![screenshot from 2016-04-28 17-34-46](https://cloud.githubusercontent.com/assets/16384828/14885158/88cebdfc-0d67-11e6-97fa-28c64d33429b.png).
But I don't know how to store the user profiles in database.I create a database class  for storing the profile given as below
![screenshot from 2016-04-28 17-41-13](https://cloud.githubusercontent.com/assets/16384828/14885331/76ee205e-0d68-11e6-8bb2-05e6c11782ce.png)
I don't know wether it is correct or not.Please a give a suggestion for creating a database.
Where I create a database in local or server.How to create a database in local.
Here the giving a addprofiles class
![screenshot from 2016-04-28 17-44-24](https://cloud.githubusercontent.com/assets/16384828/14885415/df7c3412-0d68-11e6-8468-77b3806b4a29.png)
here the addprofiles.xml file

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context="treehou.se.habit.AddProfiles">

```
<TextView
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:text="Enter your Profiles:"
    android:id="@+id/textView"
    android:layout_alignParentTop="true"
    android:layout_centerHorizontal="true"
    android:textSize="20dp"
    android:textColor="#000000" />

<EditText
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:id="@+id/editText"
    android:layout_below="@+id/textView"
    android:layout_centerHorizontal="true"
    android:textColor="#000000" />

<Button
    style="?android:attr/buttonStyleSmall"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:text="save"
    android:onClick="addProfiles"
    android:id="@+id/btnsave"
    android:layout_below="@+id/editText"
    android:textColor="#000000" />
```

</RelativeLayout>
Thanks,
Amar.

**Comment by ibaton** [comment]
@amarpulli544 . Take a look at https://github.com/ibaton/3House/issues/81 
Would be awesome if you stoped opening new issues to get an answer.
