### ISSUE TITLE
[Feature Request] Ability to hide Sitemaps

### ISSUE THREAD

**Issue by Flole998** [ibaton/3House#88]
I request a feature to hide certain sitemaps from the sitemaps view. I have one sitemap that is used for homekit-communication and is therefore not really a usable sitemap. Also I have a testing-sitemap which I would like to hide in the App. Hiding the Sitemap could either be an option on the client side or even better on the server side.

**Comment by ibaton** [comment]
@Flole998 I agree with you, will think of a solution for it.

**Comment by ibaton** [comment]
Implemented
